project:
  type: website
  output-dir: _site

website:
  title: "OHDSI EU 2026 Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: CohortConstructor/index.qmd
        text: CohortConstructor
      - href: PhenotypeR/index.qmd
        text: PhenotypeR
  page-footer:
    right:
      - icon: github
        href: https://github.com/ohdsi/OHDSI-EU-2026-Workshop

format:
  html:
    theme: cosmo
    toc: true
